### ISSUE TITLE
Making a release with monadic initialization

### ISSUE THREAD

**Issue by Jasagredo** [stevana/quickcheck-state-machine#17]
The way one defines state machines after https://github.com/stevana/quickcheck-state-machine/pull/12 has changed to requiring that the initialization is monadic. Could a new release of `quickcheck-state-machine` be published with these changes to Hackage? We would like to get rid of `source-repository-package`s [in our project](https://github.com/input-output-hk/ouroboros-network/blob/c9792d846109302185b7bbfb7daae64fa0986fb0/cabal.project#L152-L156) :smile:

**Comment by Jasagredo** [comment]
I don't want to put any pressure on you, just pinging in case this issue passed inadvertent @stevana. Sorry for the ping in advance :pray:

**Comment by stevana** [comment]
Done!
