### ISSUE TITLE
Change name of `forall` to something else in anticipation for upcoming GHC change

### ISSUE THREAD

**Issue by stevana** [stevana/quickcheck-state-machine#3]
> The GHC Proposal 281 “Visible forall” proposes to make ‘forall’ a keyword, so it will no longer be a valid identifier. Library authors are advised to use ‘forAll’, ‘forall_’, or any other name instead. The proposal is currently underconsideration by the GHC Steering Committee and is recommended for acceptance.

**Comment by jasagredo** [comment]
Done in #49
