### ISSUE TITLE
Release QSM 0.9.0 in Hackage

### ISSUE THREAD

**Issue by jasagredo** [stevana/quickcheck-state-machine#36]
We have adopted the `no-vendored-treediff` sublibrary in our test-suites (see [here](https://github.com/IntersectMBO/ouroboros-consensus/blob/main/ouroboros-consensus/ouroboros-consensus.cabal#L384) using [this adaptor module](https://github.com/IntersectMBO/ouroboros-consensus/blob/main/ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ToExpr.hs)).

However, we can't release our code until QSM 0.9.0 is released. We can upload a temporal fork-ish version to [CHaP](https://chap.intersectmbo.org) with version number 0.8.0.0.0.0.0.1 (like we have done with `persistent` for example [see](https://chap.intersectmbo.org/package/persistent-2.14.5.0.0.0.0.0.1/)) until we get Hackage's 0.9.0 but if you were planning to do a release soon we might as well just avoid doing that and depend on 0.9.0 from Hackage directly.

**Comment by stevana** [comment]
Done.

I've also started to try to automate the release process in: https://github.com/stevana/quickcheck-state-machine/pull/37/commits/a42ebd38d6e1480a01f0448e0e999d1723cf10db . It's not quite right yet, as it published on merely opening the PR whereas it should only publish on merge to master. Need to figure out how to set up the appropriate condition in CI, ideas are welcome!
