### ISSUE TITLE
Move repetitions of parallel state machine cases upwards in the chain

### ISSUE THREAD

**Issue by jasagredo** [stevana/quickcheck-state-machine#42]
Some of the recent complications that were added/proposed to QSM were due to the fact that parallel testing will perform multiple repetitions, so what seems to be a unique execution from outside is in fact multiple executions. I am wondering whether this is a good thing. This just leads to a lot of complications, namely:

- State machines have to be initialized with `WithSetup` variants to make sure it happens for each repetition

- That state machine's scope cannot escape the execution, therefore we can't check properties on the environment

- We provide multiple histories to the `prettyParallelCommands` function, which then has to do some shenanigans to juggle those executions (some might fail, others don't).

I wonder if all these complications just go away if instead of running the state machine N times in `runParallelCommands` (10 by default) we would instead generate one case and run 10 times a single execution of the parallel set of commands. I think it should be equivalent in testing power and the execution of the state machine will be isolated, which means that we could get rid of the `WithSetup` variants, there would be no need for `finalCheck` and `prettyParallelCommands` would be simplified.

The only tradeoff I can think of is that we would not be able to provide information on whether some repetitions passed and others failed. But perhaps this could still be done by grouping all the properties?

**Comment by jasagredo** [comment]
In particular what I'm proposing is moving the `replicateM` upwards into the `forallParallelCommands` and remove it from `runParallelCommands`.

**Comment by stevana** [comment]
I've never thought about moving `replicateM` upwards, but this is the kind of thing I meant when I said the following in the other issue:

> I don't like how we keep extending the StateMachine record to handle various corner cases, this seems to suggest that the API we got isn't flexible enough. Can you think of ways, perhaps inspired by the APIs of other state machine based testing libraries, which simplify the API (rather than complicate it) while solving your problem?

I still don't understand exactly what you mean that the tradeoff is, but if we can get rid of `withSetup`  and `finalCheck` I think that would be a step in the right direction.

**Comment by jasagredo** [comment]
The tradeoff I mean is that now we construct a property out of a list of histories in `prettyParallelCommands`. As we have all the histories we can see if all failed or only some failed, which indicates whether there can be a logic bug or it seems it is a race condition.

In this proposal, we would have something like:
```
foldl (.&&.) (property True) $ replicate numReps $ prop cmds
```
Because each invocation will call `prettyParallelCommands` on its own.

I have a skeleton of an implementation like:
```haskell
forAllParallelCommandsNTimes :: (Show (cmd Symbolic), Show (resp Symbolic), Show (model Symbolic))
                       => (Rank2.Traversable cmd, Rank2.Foldable resp)
                       => StateMachine model cmd m resp
                       -> Maybe Int
                       -> Int
                       -> (ParallelCommands cmd resp -> Property)     -- ^ Predicate.
                       -> Property
forAllParallelCommandsNTimes sm mminSize reps prop =
  forAllShrinkShow (generateParallelCommands sm mminSize) (shrinkParallelCommands sm) ppShow
    (\parCmds -> foldl (.&&.) (property True) $ replicate reps $ prop parCmds)

runParallelCommandsOnce :: (Show (cmd Concrete), Show (resp Concrete))
                          => (Rank2.Traversable cmd, Rank2.Foldable resp)
                          => (MonadMask m, MonadUnliftIO m)
                          => m (StateMachine model cmd m resp)
                          -> ParallelCommands cmd resp
                          -> PropertyM m (History cmd resp, model Concrete, Logic)
runParallelCommandsOnce msm cmds = do
    hchan <- newTChanIO
    ((hist, model, reason1, reason2), sm') <- run $
      fst <$> generalBracket
              msm
              (\sm' ec -> case ec of
                            ExitCaseSuccess ((_, model, _, _), _) -> cleanup sm' model
                            _ -> getChanContents hchan >>= cleanup sm' . mkModel sm' . History
              )
              (\sm' -> (,sm') <$> executeParallelCommands sm' cmds hchan True)
    return (hist, model, logicReason (combineReasons [reason1, reason2]) .&& linearise sm' hist)

prettyParallelOnceCommandsWithOpts :: (MonadIO m, Rank2.Foldable cmd)
                              => (Show (cmd Concrete), Show (resp Concrete))
                              => ParallelCommands cmd resp
                              -> Maybe GraphOptions
                              -> (History cmd resp, a, Logic) -- ^ Output of 'runParallelCommands'.
                              -> PropertyM m ()
prettyParallelOnceCommandsWithOpts cmds mGraphOptions (h, _, l) = do
  printCounterexample h (logic l) `whenFailM` property (boolean l)
    where
      printCounterexample hist' (VFalse ce) = do
        PP.putDoc $
          mconcat
           [ PP.line
           , PP.string (show $ toBoxDrawings cmds hist')
           , PP.string (show $ simplify ce)
           , PP.line
           ]
        case mGraphOptions of
          Nothing       -> return ()
         Just gOptions -> createAndPrintDot cmds gOptions hist'
      printCounterexample _hist _
        = error "prettyParallelCommands: impossible, because `boolean l` was False."
```

which can be used as:
```haskell
prop_parallel'' :: Bug -> Property
prop_parallel'' bug = forAllParallelCommandsNTimes sm' Nothing 10 $
  \cmds -> checkCommandNamesParallel cmds $ monadicIO $ do
    prettyParallelOnceCommandsWithOpts cmds Nothing =<< runParallelCommandsOnce (pure sm') cmds
    where
      sm' = sm bug
```

But I'm unsure it is working the way it should. I didn't have time to confirm it yet.
