### ISSUE TITLE
Fix "Module ‘Text.PrettyPrint.ANSI.Leijen’ is deprecated" warnings

### ISSUE THREAD

**Issue by stevana** [stevana/quickcheck-state-machine#44]
> Deprecated: Compatibility module for users of ansi-wl-pprint - use Prettyprinter instead
(https://hackage.haskell.org/package/ansi-wl-pprint-1.0.2/docs/Text-PrettyPrint-ANSI-Leijen.html)

**Comment by erikd** [comment]
Had a quick look at this. Just replacing the `ansi-wl-print` with `pretttyprinter` is pretty trivial. The hard part comes with all the color annotations which I was not able to figure out.

**Comment by jasagredo** [comment]
@erikd I swapped to `prettyprinter` in my branch. The colors come from `prettyprinter-ansi-terminal`.

**Comment by jasagredo** [comment]
Done in #49
