### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by jasagredo** [stevana/quickcheck-state-machine#45]
Hi!

Could you release a new version of QSM with #43 included? We are about to release [something](https://github.com/IntersectMBO/ouroboros-consensus/blob/utxo-hd-8.9/cabal.project#L42) that depends on this version of the library and we would like to do so without a `source-repository-package` stanza.

Thanks!

**Comment by stevana** [comment]
Can you please create a PR which documents all changes since the last release in CHANGELOG.md and bumbs the version in .cabal?

**Comment by jasagredo** [comment]
Done in #48

**Comment by stevana** [comment]
Released.
